version: '3.7'

services:
  app:
    container_name: nuovosito100
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3008:3008
    environment:
      - CHOKIDAR_USEPOLLING=true    
    restart: always

